services:
  - type: web
    name: love-u-3000
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
